### ISSUE TITLE
Scheduled data pipeline

### ISSUE THREAD

**Issue by operte** [CorrelAid/paris-bikes#64]
Melanie asked if the maps could be updated as new data is available. I guess this would be possible to achieve by scheduling the data pipelines to connect to the various data APIs and recomputing the feature table.

Do we wanna do that? Looks like a bit of work, but it could be technically interesting. It would be a lot of playing around with whatever hosting environment we choose and also developing the connections to the raw data APIs.

**Comment by Liyubov** [comment]
as i understand now the IT team will first indeed look at the whole repos and then maybe create issues, when something does not work for them, at least that was my understanding. tnx.

**Comment by operte** [comment]
Yeah agreed, let's drop it. I would like to learn about it but to be honest I don't have much availability now. I'll close the task :)
